info:
  contact: {}
paths:
  /index:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - main page
  /user/createUser:
    get:
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: password
        in: query
        name: password
        type: string
      - description: rePassword
        in: query
        name: rePassword
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Create an user
      tags:
      - Create User
  /user/deleteUser:
    get:
      parameters:
      - description: id
        in: query
        name: id
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Delete an user
      tags:
      - Delete User
  /user/list:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Get all the user as a list
      tags:
      - get user list
  /user/login:
    post:
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: password
        in: query
        name: password
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Login as a user
      tags:
      - Login
  /user/updateUser:
    post:
      parameters:
      - description: id
        in: formData
        name: id
        type: string
      - description: name
        in: formData
        name: name
        type: string
      - description: password
        in: formData
        name: password
        type: integer
      - description: phone
        in: formData
        name: phone
        type: string
      - description: email
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Update an user
      tags:
      - Update User
swagger: "2.0"
